# 공통 설정 (모든 환경에 적용)
spring:
  profiles:
    active: local  # 기본 프로파일
    include: oauth
  main:
    banner-mode: off
  thymeleaf:
    cache: true
    suffix: .html
    prefix: classpath:/templates/pages/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 1000
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: ilike.ildrio.mapper
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.web: debug  # HTTP 요청/응답 디버깅
    ilike.ildrio: debug             # 프로젝트 디버깅

server:
  port: 8093
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, image/jpeg

# JWT 설정 (공통)
jwt:
  secret: V3JpdGUtYS1zZWN1cmUtc2VjcmV0LXN0cmluZy1oZXJlLXZlcnktbG9uZyEhIQ==  # 예시: base64 인코딩된 256비트 이상 키
  expiration: 3600000  # 1시간 (밀리초 단위)

---

# ▶ 로컬 프로파일 (local)
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    log-request-details: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mariadb://211.237.0.167:3306/ACEWORK_DB
    username: root
    password: ildrio11111#db
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3

image:
  base-folder: images

---

# ▶ 운영 프로파일 (prod)
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:mariadb://211.237.0.167:3306/ACEWORK_DB
    username: root
    password: ildrio11111#db
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

image:
  base-folder: /home/ilikekim/UPLOADS

