spring:
  security:
    oauth2:
      client:
        useCurrentUri: true
        registration:
          google:
            client-id: 167481746234-v1cq5ls7ksn4leklhnuk70ibu009t50h.apps.googleusercontent.com
            client-secret: Lmc3rLeB-cpv_o-vT17_Ex5p
            scope: profile, email
          naver:
            client-id: VFggx0dZDIn7Z5xGOV4z
            client-secret: 32m2j6K4he
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          kakao:
            client-id: f2d3309171bf5f0e9270c1528717c7ab
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id   

            
